#!/usr/bin/env bash
set -eo pipefail

./main.py --port 5765 --database ":memory:" &
while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:5765 &> /dev/null; do
  sleep 0.1
done

echo
echo "===== Running tests  ====="
echo

hurl --error-format=long --test tests/*.hurl || true

echo
echo "===== Tests finished ====="
echo

pkill -INT -P $$
wait
